# Configuration for request.sh implementation.

# Patrick Lavallee Delgado
# Harris School of Public Policy
# University of Chicago
# January 2020

# Specify the geography and the name of the table in which to store these data.
geography: county
table: flow
endpoint: https://api.census.gov/data/!!YEAR!!/acs/flows?

# Specify API endpoints and variables by year.
2009:
  GEOID2: county_last_year
  MOVEDOUT: flow
2010:
  GEOID2: county_last_year
  MOVEDOUT: flow
2011:
  GEOID2: county_last_year
  MOVEDOUT: flow
2012:
  GEOID2: county_last_year
  MOVEDOUT: flow
2013:
  GEOID2: county_last_year
  MOVEDOUT: flow
2014:
  GEOID2: county_last_year
  MOVEDOUT: flow
2015:
  GEOID2: county_last_year
  MOVEDOUT: flow
2016:
  GEOID2: county_last_year
  MOVEDOUT: flow
2017:
  GEOID2: county_last_year
  MOVEDOUT: flow
2018:
  GEOID2: county_last_year
  MOVEDOUT: flow
